### ISSUE TITLE
fatal error: google/protobuf/compiler/code_generator.h: No such file or directory

### ISSUE THREAD

**Issue by Generalomosco** [grpc/grpc-web#284] opened 2018-09-07 17:53 UTC
What should caused this error below when tried to compile grpc-web on windows

```
C:\PRT\gRPC\grpc-web\javascript\net\grpc\web>make 
g++ -std=c++11 -I/usr/local/include -pthread  -c -o grpc_generator.o grpc_generator.cc grpc_generator.cc:20:53: fatal error: google/protobuf/compiler/code_generator.h:
 No such file or directory
 #include <google/protobuf/compiler/code_generator.h>
                                                     ^
compilation terminated.
make: *** [grpc_generator.o] Error 1
```

```
C:\PRT\gRPC\grpc-web\javascript\net\grpc\web>make install-plugin
make: *** No rule to make target `install-plugin'.  Stop.
```

![image](https://user-images.githubusercontent.com/17610332/45234958-a1f99000-b2d7-11e8-8ad3-4d4f0e7fa46d.png)

**Comment by stanley-cheung** [comment] 2018-09-07 18:17
Dupe of #250

**Closed by stanley-cheung** 2018-09-07 18:17 UTC
