### ISSUE TITLE
Typescript generated ToObject types doesn't work with nested types

### ISSUE THREAD

**Issue by johnmillage** [grpc/grpc-web#500] opened 2019-03-19 17:49 UTC
I you have nested types in your .proto file the .d.ts typescript files will generate the AsObject type helpers incorectly.  They will have nested types as there actual message type instead of the corresponding AsObject type.  The javascript works correctly so this is just an issue with the typescript generation.

**Comment by stanley-cheung** [comment] 2019-03-22 07:28
This *might* have been fixed via #430? I am not entire sure. It probably doesn't. But just in case, can you check the released version of `1.0.4` to see if the issue is fixed?

**Comment by shaxbee** [comment] 2019-03-25 13:09
This is fixed as of `1.0.4`.
Example:
https://github.com/shaxbee/grpc-web-dts-example/blob/master/master/example/example_pb.d.ts

**Closed** 2019-03-25 20:46 UTC
