### ISSUE TITLE
小程序使用rgpc-web报错：proto is not defined

### ISSUE THREAD

**Issue by liangfangyin** [grpc/grpc-web#940] opened 2020-08-28 11:10 UTC
使用h5的时候不报错，在微信小程序错误如下
VM17:1 MiniProgramError
proto is not defined
ReferenceError: proto is not defined
    at Object.14 (http://127.0.0.1:55390/appservice/common/vendor.js:26:278)
    at l (http://127.0.0.1:55390/appservice/common/runtime.js:32:91)
    at Object.12 (http://127.0.0.1:55390/appservice/common/vendor.js:18:103)
    at l (http://127.0.0.1:55390/appservice/common/runtime.js:32:91)
    at Object.<anonymous> (http://127.0.0.1:55390/appservice/common/vendor.js:14:195)
    at Object.11 (http://127.0.0.1:55390/appservice/common/vendor.js:14:14949)
    at l (http://127.0.0.1:55390/appservice/common/runtime.js:32:91)
    at Object.<anonymous> (http://127.0.0.1:55390/appservice/common/main.js:13:15)
    at Object.<anonymous> (http://127.0.0.1:55390/appservice/common/main.js:32:6)
    at l (http://127.0.0.1:55390/appservice/common/runtime.js:32:91)

**Comment by stanley-cheung** [comment] 2020-08-28 18:45
`proto is not defined` seems to be dupe of #447.

**Closed by stanley-cheung** 2020-08-28 18:45 UTC
