### ISSUE TITLE
Unary callback executed multiple times on gRPC error

### ISSUE THREAD

**Issue by ascherkus** [grpc/grpc-web#632] opened 2019-09-10 18:42 UTC
I notice on HTTP/1.1 200 responses with a valid gRPC error that the callback is being executed three times. I believe it's a result of having a non-OK status code, which leads to executing the callback twice on "status" events and once more on the "error" event in `grpcwebclientbase.js`.

I found this to be surprising behavior (I expected at most a single non-null error callback), and since the callback is a required parameter I either have to use a local variable to track whether a non-null error has been previously encountered to prevent triggering error logic multiple times _or_ pass in no-op callback and use the returned `ClientReadableStream` object.

Example server code (Go):
```
func (s *server) Foo(context.Context, *foo.FooRequest) (*foo.FooResponse, error) {
	return nil, status.Error(codes.Unimplemented, "unimplemented")
}
```

Example client code (Typescript):
```
let client = new FooClient("http://localhost:8888");
let req = new FooRequest();
client.foo(req, null, function(err, resp) {
  console.log(err);
  console.log(resp);
  console.trace();
});
```

Console output:
```
{code: 12, message: "unimplemented"}
null
[ stack trace where "status" callback is triggered ]
{code: 12, message: "unimplemented"}
null
[ stack trace where "status" callback is triggered ]
{code: 12, message: "unimplemented"}
null
[ stack trace where "error" callback is triggered ]
```

I'm curious whether this is intended behavior or not (the double-status event in particular seems odd).

If not, I've got a few ideas:
1. Make the callback an optional parameter
2. Remove the callback entirely to support/force a consistent coding approach (i.e., same as streaming)
3. Don't execute the callback for status updates (i.e., only execute on "data" or "error")
4. Call the callback at most once on the first non-OK status/error response (whichever comes first)

Environment details:
  - protoc-gen-grpc-web-1.0.6-darwin-x86_64 
  - protoc 3.7.1
  - `--js_out=import_style=commonjs:$OUT`
  - `--grpc-web_out=import_style=typescript,mode=grpcweb:$OUT`
  - "google-protobuf": "^3.10.0-rc.1"
  - "grpc-web": "^1.0.6"
  - Server using `github.com/improbable-eng/grpc-web/go/grpcweb`

**Comment by stanley-cheung** [comment] 2019-09-11 23:26
This is probably fixed in #608, that hasn't been released yet. Will be included in the next release, namely `1.0.7`.

**Comment by vsile** [comment] 2020-04-30 23:52
On 01 May 2020 I steel have the issue.

**Comment by AdamiHamza** [comment] 2020-05-13 00:01
Still having this issue 😞

**Comment by stanley-cheung** [comment] 2020-06-02 07:00
This is probably fixed in `1.1.0`. If this is still an issue, please re-open.

**Closed** 2020-06-10 00:38 UTC

**Comment by ascherkus** [comment] 2020-06-10 01:49
Thanks for the fix!! I'll give it whirl!

**Comment by stanley-cheung** [comment] 2020-06-10 02:08
Just to clarify a few things, related to this particular issue:

- #847 should fix the "calling `.on()` will _override_ the existing callback" problem. Now you should be able to add multiple callbacks to the same event, and they will each be called in sequence. There is also a new `removeListener()` method to remove a callback you added.

- This should also fix the problem where either the `error` or the `status` callback is being called multiple times per RPC. If there is an error, the unary callback `(err, response) => {}` should only be called once now, with `err` being populated. Same for the `status` callback, in itself, should only be called once.

- Now, with regard to `status` and `error` both being called on an error, I think that's by design. The `status` callback is being called to return the "trailers", containing the grpc status code, message and the set of trailing metadata, regardless of the rpc ending in OK or not. It's a common use case to return extra metadata to the user via the `status` callback even on successful (status code = OK) RPC. In that case, the `error` callback won't fire.  Now let's say an RPC ends in an error, that's being communicated via the trailers. The `error` callback should trigger - that makes sense. But it also makes sense to trigger the `status` callback because indeed a trailer frame has been received. It's up to the user how to interpret them in conjunction.
