### ISSUE TITLE
Why does grPC-Web start the Stream connection and do nothing but slowly increase the browser memory until it crashes

### ISSUE THREAD

**Issue by mei2015** [grpc/grpc-web#920] opened 2020-08-07 01:56 UTC
为什么grpc-web 一开启stream连接什么都不做 浏览器内存就开始慢慢增加直至崩溃
Why does grPC-Web start the Stream connection and do nothing but slowly increase the browser memory until it crashes

**Comment by stanley-cheung** [comment] 2020-08-19 21:23
Dupe of #714.

**Closed by stanley-cheung** 2020-08-19 21:23 UTC
