### ISSUE TITLE
Reduce compiled JS file size

### ISSUE THREAD

**Issue by stanley-cheung** [grpc/grpc-web#270] opened 2018-08-29 05:43 UTC
As it stands, our [npm package](https://www.npmjs.com/package/grpc-web) `index.js` is 218KiB (which is being compiled by the closure compiler [here](https://github.com/grpc/grpc-web/blob/master/packages/grpc-web/scripts/build.js)).

With the [Echo example echo.proto](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/echo.proto), that has about 7 message types, 1 service, 3 unary methods and 5 streaming methods:
- The [Closure example](https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/Makefile#L60) final `compiled.js` compiled by the Closure compiler: 317KiB
 - The [CommonJS example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/commonjs-example) final `dist/main.js` compiled by `webpack`: 415KiB
 - The same CommonJS example compiled by `browserify`: 479KiB
 - The CommonJS example [with `.d.ts` typings](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/echo/ts-example) generated, and then compiled by `webpack`: 499KiB

I tried `babel-minify` and `uglify-js` on some of these JS files and the output are not any particularly smaller.

There should be some other things we can do to further minimize the compiled JS code size.

Reference: #79

**Comment by color-infinispace** [comment] 2018-08-29 05:49
@stanley-cheung   could you check the size of compiled JS for protobuf messages?

**Comment by stanley-cheung** [comment] 2018-08-29 06:01
A bit more info, as it stands:
 - the generated protobuf messages `echo_pb.js` produced by `--js_out`: 35KiB
 - the generated gRPC Web stub `echo_grpc_web_pb.js` produced by `--grpc-web_out`: 9KiB

A couple more observations:
 - Just by looking at `compiled.js`, `dist/main.js` produced by the closure compiler, webpack, etc, the compiled JS files are already reasonably minimized. Most variables are already renamed, whitespace removed, etc.
 - From a cursory look, the largest increase of code size is caused by  1. proto messages pulling in `google-protobuf` runtime classes and 2. grpc-web service stub pulling in `goog.net.streams` and closure library code. But again, after those dependencies are pulled in, the resulting code are already reasonably minimized.

**Comment by wenbozhu** [comment] 2018-08-29 06:13
For the protobuf messages, could you check the compiled.js with out the protobuf  messages.

I.e. it is useful to find out the respective sizes of google-protobuf v.s. goog.net.streams

**Comment by wenbozhu** [comment] 2018-12-17 20:40
@codesuki  could you share the generated code size v.s. dependencies respectively for your front-end project?  Optimizing protobuf-JS is not something we could do easily but grpc-web stub and runtime may have room for optimization.

**Comment by jjbubudi** [comment] 2018-12-27 10:52
Will need to dig into the bundled code but at a glance I believe it's because of the same reason as this:
https://github.com/protocolbuffers/protobuf/pull/5509

Currently in `build.js`, it looks like closure compiler's advanced optimizations feature is not turned on, so the bundle ended up containing redundant code because there is no tree shaking. To fix this we will need to:
1. Turn on advanced optimizations
2. Add `@export` to the public APIs and let closure compiler advanced mode safely performs tree shaking

Will get back on this thread once I confirmed this. If it works it would drastically reduce the bundle size.

**Comment by jjbubudi** [comment] 2018-12-27 10:58
FYI, as of v1.0.3 the bundle size of `grpc-web` alone is:
- 217.4KB minified, uncompressed
- 51.4KB minified, gzipped

Ref: https://bundlephobia.com/result?p=grpc-web@1.0.3

**Comment by Yannic** [comment] 2018-12-27 17:10
I think @jjbubudi is right, I'm seeing smaller bundle sizes and we use advanced optimizations for all our code (I don't have exact numbers to share here because there is more compiled into our bundles, but our files are smaller than the sizes mentioned above).

If we go ahead and add `@export` annotations to the public APIs, can we do that in separate files, or at least add an option to turn that on/off? Otherwise, those of us who use it directly from closure-style code will export these symbols when there is no need to.

**Comment by Yannic** [comment] 2018-12-27 18:11
Wow, that's great news @jjbubudi!
Unfortunately, `--generate_exports` won't help in my case. We use `@export` in our library to export public parts of the API.

However, `@export` is translated to `goog.export{Symbol,Property}`. Manually writing these and guarding them by a compile-time constant would be an option. It's a tiny bit more work, but doesn't increase the compiled size because of dead code elimination. I think it's worth it if we can avoid exporting unnecessary symbols.

```javascript
/** @const {boolean} */
const EXPORT_GRPC_WEB_SYMBOLS = true;

function foo() {}
if (EXPORT_GRPC_WEB_SYMBOLS) {
  goog.exportSymbol('foo', foo);
}
```

Let me know when you submit your PR.

**Comment by jjbubudi** [comment] 2018-12-27 18:44
Ah, ok. I've submitted PR #422. Looks like it needs to be further updated to avoid affecting existing Closure users.

**Comment by jjbubudi** [comment] 2018-12-28 14:51
@Yannic Actually, looking deeper at the optimized code, Closure Compiler has stripped away all the `goog.exportX` calls and merely leaving 1 little line of prototype alias code. I'd think when using `@export` the increase in code size should be negligible but we gain a lot in maintainability.

Here is the pretty printed version of the new bundle FYI: https://gist.github.com/jjbubudi/86549bd597ffc4d74b30990e7a385f44#file-grpc-web-js-L1287

**Comment by nehbit** [comment] 2019-04-04 18:51
Did @jjbubudi's fix ever end up being available? I've encountered the same issue — with a trivial ```hello world``` proto, the smallest my bundle got was 180~Kb with Webpack, of which, only 8Kb is actual application code. The rest appears to be grpc-web. This is a problem because our web app targets mobile devices, we simply don't have the ability to add +180Kb to our payload, our landing page in total is smaller than that. 

Thanks for the hard work — it otherwise works very well. I would just love to be able to strip away the google-protobuf's unused parts somehow, preferably with Webpack.

**Comment by lePereT** [comment] 2019-06-05 07:58
https://github.com/grpc/grpc-web/pull/469#issue-254871907

**Comment by jjbubudi** [comment] 2019-06-05 08:23
@nehbit It went into 1.0.4, see https://bundlephobia.com/result?p=grpc-web@1.0.4

**Comment by mleonhard** [comment] 2019-12-23 23:22
I built six single-field protos and my bundle.js grew by 332 KiB.  This is unacceptable.  So far, it seems to me that the only solution offered is to learn a new language (Closure) and translate our code to it.  Is this correct?

Now I will try Protobuf.js.

**Comment by clehene** [comment] 2020-09-03 16:22
> I built six single-field protos and my bundle.js grew by 332 KiB.  This is unacceptable.  So far, it seems to me that the only solution offered is to learn a new language (Closure) and translate our code to it.  Is this correct?
> 
> 
> 
> Now I will try Protobuf.js.

I believe the references are to the [Closure compiler](https://developers.google.com/closure/compiler)

**Comment by PeteX** [comment] 2021-12-14 00:13
I just built a simple "hello world" test, and ended up with about 250k of minified Javascript.  The [comments above](https://github.com/grpc/grpc-web/issues/270#issuecomment-498987327) suggest that this issue should be resolved.  Am I doing something wrong or is there still a problem somewhere?

By the way, thank you for all your work on this.  I believe grpc-web will be the future of client-server communications on the web, even though there might be a few blocks at the moment.

**Comment by sampajano** [comment] 2021-12-17 07:59
@PeteX thanks for the update and your kind comment! :)

Not having much context of this issue myself, i just tried to build the helloworld example

**Comment by PeteX** [comment] 2021-12-17 23:24
Thanks, I think I understand the situation now.

**Comment by sayjeyhi** [comment] 2022-07-28 17:20
In 2022, `google-protobuf` has about 45Kb gzipped size... (230KB minified)

**Comment by egor-yolabs** [comment] 2022-08-01 19:41
Why was this issue closed?
As it stands now this library is unusable for a serious, production web project due the unreasonably large dependency size. Having this issue open would at least let developers know to steer clear.

**Comment by sampajano** [comment] 2022-08-02 18:58
@egor-yolabs Hi Egor thanks for the input :)

I guess i closed it because the majority of the code size is due to the use of protobuf JS.

There isn't much we could do on our side since it's a required dependency.

If you'd like, maybe you could consider filing a bug against https://github.com/protocolbuffers/protobuf-javascript per the comment in https://github.com/grpc/grpc-web/issues/270#issuecomment-996512398 and https://github.com/grpc/grpc-web/issues/270#issuecomment-1198428226?

Thanks! :)

**Comment by sampajano** [comment] 2022-08-02 19:00
I think we can keep it open for now, but we need to decide on a "reasonable" size so we know what's the target :)

**Comment by egor-yolabs** [comment] 2022-08-02 19:14
I see that @sayjeyhi recently logged https://github.com/protocolbuffers/protobuf-javascript/issues/124 with them which is related to this issue.
What seems very odd to me, is that the entire google-protobuf is being pulled in even if only a tiny part of the library was actually used. Ex. `goog.exportSymbol()` and `goog.object.extend()`. I wonder if tree shaking is not working properly for google-probuf for webpack (which I assume we're all using here) because that lib's package.json doesn't list a `"sideEffects": false`.

**Comment by sampajano** [comment] 2022-08-06 16:56
> What seems very odd to me, is that the entire google-protobuf is being pulled in even if only a tiny part of the library was actually used.

I'm curious what's the reason you think the dependency we have pulled in is a tiny part of the library, and should not in turn pull in the majority of the protobuf library?

if you are aware of any kind of static analysis that would show the percentage of the library we should in fact pull in, it would be helpful :)

**Comment by egor-yolabs** [comment] 2022-08-08 22:56
> > What seems very odd to me, is that the entire google-protobuf is being pulled in even if only a tiny part of the library was actually used.
> 
> I'm curious what's the reason you think the dependency we have pulled in is a tiny part of the library, and should not in turn pull in the majority of the protobuf library?
> 
> if you are aware of any kind of static analysis that would show the percentage of the library we should in fact pull in, it would be helpful :)

You may not have understood what I meant. I see you ran the webpack-bundle-analyzer above which is what I've been running too on my project. In my project, I have a very simple case which imports the generated enums that were generated from some very simple protos (no service definitions). The generated  code contains only two references to `google-protobuf` which are `goog.exportSymbol()` and `goog.object.extend()` as mentioned above. In theory here, webpack should tree shake away the unused parts of `google-protobuf` as there's no way that those two functions require the vast functionality that is provided by that package. Yet the entirety of `google-protobuf` is pulled into the bundle that we're all experiencing here. This tells me that tree shaking is somehow broken here. The typical culprit is forgetting to add `sideEffects: false` to the package.json which is a signal to webpack that the package doesn't do some crazy shit like dynamically importing using variables which makes it difficult to figure out precisely which parts may be tree shaken out or not. It doesn't appear that using that package.json property does anything here, so I'm not sure exactly why tree shaking is not working.

Regardless of that, it looks like someone finally figured out how to do grpc in the browser correctly: https://github.com/bufbuild/connect-web
I'm only waiting on them to add node.js support after which this grpc-web repo may as well be deprecated as far as I am concerned. I see that they wrote their own protoc plugin, which I'm guessing is the key to this issue. I have not tested any of it yet, but it sounds very promising.

**Comment by sampajano** [comment] 2022-08-08 23:50
> The generated code contains only two references to google-protobuf which are goog.exportSymbol() and goog.object.extend() as mentioned above. In theory here, webpack should tree shake away the unused parts of google-protobuf as there's no way that those two functions require the vast functionality that is provided by that package.

Yeah this is my question here. Would love to see an analysis of the dependency here to see if the above is indeed true.

> The typical culprit is forgetting to add sideEffects: false to the package.json ...

The grpc-web package is built using Closure compiler, and the parameters are specified [here](https://github.com/grpc/grpc-web/blob/056a1c652fc0136b596cfba10fd1b4a903b75e79/packages/grpc-web/scripts/build.js#L33-L44), where dependency pruning is already enabled.

If anyone is able to experiment with the flags can showcase a code size reduction, it would be much appreciated.

> Regardless of that, it looks like someone finally figured out how to do grpc in the browser correctly: https://github.com/bufbuild/connect-web
I'm only waiting on them to add node.js support after which this grpc-web repo may as well be deprecated as far as I am concerned. I see that they wrote their own protoc plugin, which I'm guessing is the key to this issue. I have not tested any of it yet, but it sounds very promising.

I'm glad you found a solution that works for you :)

This repo indeed may not have all the latest features, but it provides an example implementation and will stay up-to-date as the grpc-web protocol evolves.

**Comment by akshayjshah** [comment] 2022-08-15 14:53
I know very little about JS bundling and tree-shaking, but it seems that some of the foundational technology choices here and in Google's JS protobuf runtime make controlling bundle size difficult. It's understandably hard to revisit those decisions without breaking existing users. This is a great place for third-party implementations to experiment and find a better path forward. 

A good first step toward encouraging a robust gRPC-Web ecosystem would be to formalize the protocol specification: https://github.com/grpc/grpc/issues/30565

(I realize that this is a bit of a tangent, but I thought folks interested in this issue may also want to weigh in on the protocol formalization.)

**Comment by sayjeyhi** [comment] 2022-08-25 13:24
I've opened a PR(https://github.com/protocolbuffers/protobuf-javascript/pull/128) on `google-protobuf` repo to fix and remove lots of unused code there, and maybe we can have it after a new release.

**Comment by sayjeyhi** [comment] 2022-10-08 08:02
<img width="1222" alt="Screen Shot 1401-07-16 at 12 01 21" src="https://user-images.githubusercontent.com/6254009/194696972-17e1870a-c388-4efc-9539-b9a44419987e.png">

Good news guys!
The changes for reducing bundle size of `google-protobuf` is merged and the new version is out there 😍 

I am not sure do we need to update the version of this pkg to use the latest version of `google-protobuf` or not.

**Comment by sampajano** [comment] 2022-10-28 20:56
Update: Due to an issue in CommonJs, the code size optimization was rolled back in https://github.com/protocolbuffers/protobuf-javascript/pull/143.

Good new is that the team is actively working on re-enabling that optimization ([comment](https://github.com/protocolbuffers/protobuf-javascript/pull/143#issuecomment-1276479425)) 😃

@sayjeyhi FYI :)

**Comment by sampajano** [comment] 2024-07-19 22:34
FYI, `protobuf-javascript` has recently made a new [`3.21.4`](https://github.com/protocolbuffers/protobuf-javascript/releases/tag/v3.21.4) release, and it seems that they've re-enabled advanced optimization, so zipped bunch size has **reduced from 48K -> 16KB**!

![image](https://github.com/user-attachments/assets/79b8efcc-98c0-4dbb-9376-f73d001b1816)
(from https://bundlephobia.com/package/google-protobuf@3.21.4)

**Comment by sampajano** [comment] 2024-07-23 02:34
I did a test build of [helloworld example](https://github.com/grpc/grpc-web/tree/master/net/grpc/gateway/examples/helloworld) (similar to [above](https://github.com/grpc/grpc-web/issues/270#issuecomment-996512398)) using https://github.com/grpc/grpc-web/pull/1452, and analyzed the bundle size.

And the size of google-protobuf.js went **down from 230KB -> 66KB**:

- Before: **230KB** (protobuf) / 286KB (total) = **80%** of total demo bundle size
- After: **66KB** (protobuf) / 122KB (total) = **54%** of total demo bundle **size**

Before:
<img width="1137" alt="Screenshot 2024-07-22 at 7 22 22 PM" src="https://github.com/user-attachments/assets/e966289f-f930-4a47-8d74-ddd39720fa7d">

After:
<img width="1140" alt="Screenshot 2024-07-22 at 4 36 48 PM" src="https://github.com/user-attachments/assets/ad852083-09fd-4cd7-b1b9-c5afe425f8fb">

---

This is a significant improvement from before!

I recommend users to migrate to [google-protobuf](https://www.npmjs.com/package/google-protobuf) `3.21.4` and see if this makes a significant different for your project :)

I will close this issue for now and we can discuss follow-ups here and re-open or open new issues when necessary.

Thanks :)

**Closed by sampajano** 2024-07-23 02:34 UTC
