### ISSUE TITLE
Grpc-web not return exactly  grpc status always response 2 Incomplete response 

### ISSUE THREAD

**Issue by KP-story** [grpc/grpc-web#1417] opened 2024-03-29 16:38 UTC
I gen code using a command  protoc  -I=./src/proto \
  --js_out=import_style=commonjs,binary:./src/generated \
  --grpc-web_out=import_style=typescript,mode=grpcweb:./src/generated \
  $(find ./src/proto -iname "*.proto")
When I sent request that was not valid, Grpc web always response 2 incomplete response , even though my response headers contained the 'grpc-status' and 'grpc-message' fields."
<img width="889" alt="Screenshot 2024-03-29 at 23 37 12" src="https://github.com/grpc/grpc-web/assets/42842787/bc5269c3-a8e7-4b57-9720-6ff8a19056aa">

**Comment by sampajano** [comment] 2024-03-29 22:28
@KP-story Thanks for the report!

Do you mind following this following Typescript example, and check how things are looking different between that and what you have?
https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/ts-example/README.md

**Comment by KP-story** [comment] 2024-03-30 15:19
> @KP-story Thanks for the report!
> 
> Do you mind following this following Typescript example, and check how things are looking different between that and what you have? https://github.com/grpc/grpc-web/blob/master/net/grpc/gateway/examples/echo/ts-example/README.md
> 
> Without knowing your whole setup, it's hard to know what's wrong. So it would be easier if you compare the wire data against the demo we have.

HI, My backend was written by rust tonic web. I always response null with grpc-status and grpc-message in metadata. Is it valid ?

**Comment by dnprogramming** [comment] 2024-03-31 19:29
@KP-story As I see you are using CloudFlare might I recommend checking if you have access to the CloudFlare Dashboard for that website, go to the Network tab, and scroll to the bottom and make sure gRPC is enabled so it knows to proxy the gRPC API connection. https://developers.cloudflare.com/network/grpc-connections/

**Comment by KP-story** [comment] 2024-04-01 00:57
> @KP-story As I see you are using CloudFlare might I recommend checking if you have access to the CloudFlare Dashboard for that website, go to the Network tab, and scroll to the bottom and make sure gRPC is enabled so it knows to proxy the gRPC API connection. https://developers.cloudflare.com/network/grpc-connections/

Hi, I have just updated the configuration in Cloudflare, but it's still showing an error.
I wonder whether the response Content-Length being equal to zero is the cause of the error.

<img width="741" alt="Screenshot 2024-04-01 at 07 55 03" src="https://github.com/grpc/grpc-web/assets/42842787/6d40f93b-28b4-44fc-8d4a-61b5026d30cf">
<img width="711" alt="Screenshot 2024-04-01 at 07 55 14" src="https://github.com/grpc/grpc-web/assets/42842787/dde10fb6-eb14-4a49-9a42-5c8790a9edb1">

**Comment by yzc1114** [comment] 2024-06-12 12:42
@KP-story Same problem. Did you solve it?

**Comment by KP-story** [comment] 2024-06-12 14:32
Yes, I have just added "grpc-status" and "grpc-messages" to the
"Access-Control-Allow-Headers" in the preflight request.
Vào 19:42, Th 4, 12 thg 6, 2024 Zichao Yang ***@***.***> đã
viết:

**Comment by sampajano** [comment] 2024-06-12 17:54
@KP-story Thanks for the update! Glad to hear that the issue is resolved now! 😃

I will close this issue now :)

**Closed by sampajano** 2024-06-12 17:54 UTC
Labels: pending-ack
